-- Champion image column + base champion attribute seed
-- Scope:
--   1) ensure image_url column exists
--   2) upsert champion base attributes (name/image_url/roles/tier/rates)
-- champion_stat_profile score attributes are maintained in:
--   src/main/java/com/LOLCAA/domain/sql/champion_attribute_fill.sql
ALTER TABLE champion
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);

-- Full champion seed (official Data Dragon)
-- Version: 14.24.1
-- Safe to re-run (UPSERT)
INSERT INTO champion (id, name, image_url, primary_role, secondary_role, tier, pick_rate, win_rate)
VALUES
    (1, 'Annie', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Annie.png', 'MID', 'SUP', 'A', NULL, NULL),
    (2, 'Olaf', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Olaf.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (3, 'Galio', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Galio.png', 'MID', 'SUP', 'A', NULL, NULL),
    (4, 'Twisted Fate', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/TwistedFate.png', 'MID', 'TOP', 'A', NULL, NULL),
    (5, 'Xin Zhao', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/XinZhao.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (6, 'Urgot', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Urgot.png', 'TOP', 'MID', 'A', NULL, NULL),
    (7, 'LeBlanc', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Leblanc.png', 'MID', 'SUP', 'A', NULL, NULL),
    (8, 'Vladimir', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Vladimir.png', 'MID', 'SUP', 'A', NULL, NULL),
    (9, 'Fiddlesticks', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Fiddlesticks.png', 'JUNGLE', 'SUP', 'A', NULL, NULL),
    (10, 'Kayle', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kayle.png', 'TOP', 'MID', 'A', NULL, NULL),
    (11, 'Master Yi', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/MasterYi.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (12, 'Alistar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Alistar.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (13, 'Ryze', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ryze.png', 'MID', 'TOP', 'A', NULL, NULL),
    (14, 'Sion', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sion.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (15, 'Sivir', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sivir.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (16, 'Soraka', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Soraka.png', 'SUP', 'MID', 'A', NULL, NULL),
    (17, 'Teemo', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Teemo.png', 'TOP', 'MID', 'A', NULL, NULL),
    (18, 'Tristana', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Tristana.png', 'ADC', 'MID', 'A', NULL, NULL),
    (19, 'Warwick', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Warwick.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (20, 'Nunu & Willump', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nunu.png', 'JUNGLE', 'SUP', 'A', NULL, NULL),
    (21, 'Miss Fortune', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/MissFortune.png', 'ADC', 'MID', 'A', NULL, NULL),
    (22, 'Ashe', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ashe.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (23, 'Tryndamere', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Tryndamere.png', 'TOP', 'MID', 'A', NULL, NULL),
    (24, 'Jax', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jax.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (25, 'Morgana', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Morgana.png', 'SUP', 'MID', 'A', NULL, NULL),
    (26, 'Zilean', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zilean.png', 'SUP', 'MID', 'A', NULL, NULL),
    (27, 'Singed', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Singed.png', 'MID', 'SUP', 'A', NULL, NULL),
    (28, 'Evelynn', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Evelynn.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (29, 'Twitch', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Twitch.png', 'ADC', 'JUNGLE', 'A', NULL, NULL),
    (30, 'Karthus', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Karthus.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (31, 'Cho''Gath', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Chogath.png', 'MID', 'SUP', 'A', NULL, NULL),
    (32, 'Amumu', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Amumu.png', 'JUNGLE', 'SUP', 'A', NULL, NULL),
    (33, 'Rammus', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Rammus.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (34, 'Anivia', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Anivia.png', 'MID', 'SUP', 'A', NULL, NULL),
    (35, 'Shaco', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Shaco.png', 'JUNGLE', 'SUP', 'A', NULL, NULL),
    (36, 'Dr. Mundo', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/DrMundo.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (37, 'Sona', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sona.png', 'SUP', 'MID', 'A', NULL, NULL),
    (38, 'Kassadin', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kassadin.png', 'MID', 'TOP', 'A', NULL, NULL),
    (39, 'Irelia', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Irelia.png', 'TOP', 'MID', 'A', NULL, NULL),
    (40, 'Janna', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Janna.png', 'SUP', 'MID', 'A', NULL, NULL),
    (41, 'Gangplank', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Gangplank.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (42, 'Corki', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Corki.png', 'ADC', 'MID', 'A', NULL, NULL),
    (43, 'Karma', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Karma.png', 'SUP', 'MID', 'A', NULL, NULL),
    (44, 'Taric', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Taric.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (45, 'Veigar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Veigar.png', 'MID', 'SUP', 'A', NULL, NULL),
    (48, 'Trundle', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Trundle.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (50, 'Swain', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Swain.png', 'SUP', 'MID', 'A', NULL, NULL),
    (51, 'Caitlyn', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Caitlyn.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (53, 'Blitzcrank', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Blitzcrank.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (54, 'Malphite', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Malphite.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (55, 'Katarina', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Katarina.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (56, 'Nocturne', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nocturne.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (57, 'Maokai', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Maokai.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (58, 'Renekton', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Renekton.png', 'TOP', 'MID', 'A', NULL, NULL),
    (59, 'Jarvan IV', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/JarvanIV.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (60, 'Elise', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Elise.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (61, 'Orianna', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Orianna.png', 'SUP', 'MID', 'A', NULL, NULL),
    (62, 'Wukong', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/MonkeyKing.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (63, 'Brand', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Brand.png', 'SUP', 'MID', 'A', NULL, NULL),
    (64, 'Lee Sin', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/LeeSin.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (67, 'Vayne', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Vayne.png', 'ADC', 'TOP', 'A', NULL, NULL),
    (68, 'Rumble', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Rumble.png', 'TOP', 'MID', 'A', NULL, NULL),
    (69, 'Cassiopeia', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Cassiopeia.png', 'MID', 'SUP', 'A', NULL, NULL),
    (72, 'Skarner', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Skarner.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (74, 'Heimerdinger', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Heimerdinger.png', 'SUP', 'MID', 'A', NULL, NULL),
    (75, 'Nasus', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nasus.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (76, 'Nidalee', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nidalee.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (77, 'Udyr', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Udyr.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (78, 'Poppy', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Poppy.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (79, 'Gragas', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Gragas.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (80, 'Pantheon', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Pantheon.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (81, 'Ezreal', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ezreal.png', 'ADC', 'MID', 'A', NULL, NULL),
    (82, 'Mordekaiser', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Mordekaiser.png', 'MID', 'SUP', 'A', NULL, NULL),
    (83, 'Yorick', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Yorick.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (84, 'Akali', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Akali.png', 'MID', 'TOP', 'A', NULL, NULL),
    (85, 'Kennen', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kennen.png', 'TOP', 'MID', 'A', NULL, NULL),
    (86, 'Garen', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Garen.png', 'TOP', 'MID', 'A', NULL, NULL),
    (89, 'Leona', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Leona.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (90, 'Malzahar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Malzahar.png', 'MID', 'SUP', 'A', NULL, NULL),
    (91, 'Talon', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Talon.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (92, 'Riven', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Riven.png', 'TOP', 'MID', 'A', NULL, NULL),
    (96, 'Kog''Maw', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/KogMaw.png', 'ADC', 'MID', 'A', NULL, NULL),
    (98, 'Shen', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Shen.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (99, 'Lux', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lux.png', 'MID', 'SUP', 'A', NULL, NULL),
    (101, 'Xerath', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Xerath.png', 'SUP', 'MID', 'A', NULL, NULL),
    (102, 'Shyvana', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Shyvana.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (103, 'Ahri', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ahri.png', 'MID', 'SUP', 'A', NULL, NULL),
    (104, 'Graves', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Graves.png', 'JUNGLE', 'ADC', 'A', NULL, NULL),
    (105, 'Fizz', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Fizz.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (106, 'Volibear', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Volibear.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (107, 'Rengar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Rengar.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (110, 'Varus', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Varus.png', 'ADC', 'MID', 'A', NULL, NULL),
    (111, 'Nautilus', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nautilus.png', 'SUP', 'JUNGLE', 'A', NULL, NULL),
    (112, 'Viktor', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Viktor.png', 'MID', 'TOP', 'A', NULL, NULL),
    (113, 'Sejuani', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sejuani.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (114, 'Fiora', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Fiora.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (115, 'Ziggs', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ziggs.png', 'ADC', 'MID', 'A', NULL, NULL),
    (117, 'Lulu', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lulu.png', 'SUP', 'MID', 'A', NULL, NULL),
    (119, 'Draven', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Draven.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (120, 'Hecarim', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Hecarim.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (121, 'Kha''Zix', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Khazix.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (122, 'Darius', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Darius.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (126, 'Jayce', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jayce.png', 'TOP', 'MID', 'A', NULL, NULL),
    (127, 'Lissandra', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lissandra.png', 'MID', 'SUP', 'A', NULL, NULL),
    (131, 'Diana', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Diana.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (133, 'Quinn', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Quinn.png', 'TOP', 'ADC', 'A', NULL, NULL),
    (134, 'Syndra', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Syndra.png', 'MID', 'SUP', 'A', NULL, NULL),
    (136, 'Aurelion Sol', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/AurelionSol.png', 'MID', 'SUP', 'A', NULL, NULL),
    (141, 'Kayn', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kayn.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (142, 'Zoe', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zoe.png', 'MID', 'SUP', 'A', NULL, NULL),
    (143, 'Zyra', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zyra.png', 'SUP', 'MID', 'A', NULL, NULL),
    (145, 'Kai''Sa', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kaisa.png', 'ADC', 'MID', 'A', NULL, NULL),
    (147, 'Seraphine', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Seraphine.png', 'SUP', 'MID', 'A', NULL, NULL),
    (150, 'Gnar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Gnar.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (154, 'Zac', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zac.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (157, 'Yasuo', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Yasuo.png', 'MID', 'TOP', 'A', NULL, NULL),
    (161, 'Vel''Koz', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Velkoz.png', 'MID', 'SUP', 'A', NULL, NULL),
    (163, 'Taliyah', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Taliyah.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (164, 'Camille', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Camille.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (166, 'Akshan', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Akshan.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (200, 'Bel''Veth', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Belveth.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (201, 'Braum', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Braum.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (202, 'Jhin', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jhin.png', 'ADC', 'MID', 'A', NULL, NULL),
    (203, 'Kindred', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kindred.png', 'JUNGLE', 'ADC', 'A', NULL, NULL),
    (221, 'Zeri', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zeri.png', 'ADC', 'MID', 'A', NULL, NULL),
    (222, 'Jinx', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jinx.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (223, 'Tahm Kench', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/TahmKench.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (233, 'Briar', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Briar.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (234, 'Viego', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Viego.png', 'JUNGLE', 'MID', 'A', NULL, NULL),
    (235, 'Senna', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Senna.png', 'SUP', 'ADC', 'A', NULL, NULL),
    (236, 'Lucian', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lucian.png', 'ADC', 'MID', 'A', NULL, NULL),
    (238, 'Zed', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zed.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (240, 'Kled', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kled.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (245, 'Ekko', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ekko.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (246, 'Qiyana', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Qiyana.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (254, 'Vi', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Vi.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (266, 'Aatrox', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Aatrox.png', 'TOP', 'MID', 'A', NULL, NULL),
    (267, 'Nami', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nami.png', 'SUP', 'MID', 'A', NULL, NULL),
    (268, 'Azir', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Azir.png', 'ADC', 'MID', 'A', NULL, NULL),
    (350, 'Yuumi', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Yuumi.png', 'SUP', 'MID', 'A', NULL, NULL),
    (360, 'Samira', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Samira.png', 'ADC', 'MID', 'A', NULL, NULL),
    (412, 'Thresh', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Thresh.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (420, 'Illaoi', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Illaoi.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (421, 'Rek''Sai', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/RekSai.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (427, 'Ivern', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ivern.png', 'JUNGLE', 'SUP', 'A', NULL, NULL),
    (429, 'Kalista', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kalista.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (432, 'Bard', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Bard.png', 'SUP', 'MID', 'A', NULL, NULL),
    (497, 'Rakan', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Rakan.png', 'SUP', 'TOP', 'A', NULL, NULL),
    (498, 'Xayah', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Xayah.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (516, 'Ornn', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ornn.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (517, 'Sylas', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sylas.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (518, 'Neeko', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Neeko.png', 'SUP', 'MID', 'A', NULL, NULL),
    (523, 'Aphelios', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Aphelios.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (526, 'Rell', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Rell.png', 'SUP', 'JUNGLE', 'A', NULL, NULL),
    (555, 'Pyke', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Pyke.png', 'SUP', 'MID', 'A', NULL, NULL),
    (711, 'Vex', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Vex.png', 'MID', 'SUP', 'A', NULL, NULL),
    (777, 'Yone', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Yone.png', 'MID', 'TOP', 'A', NULL, NULL),
    (799, 'Ambessa', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ambessa.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (800, 'Mel', 'https://ddragon.leagueoflegends.com/cdn/16.7.1/img/champion/Mel.png', 'SUP', 'MID', 'A', NULL, NULL),
    (804, 'Yunara', 'https://ddragon.leagueoflegends.com/cdn/16.7.1/img/champion/Yunara.png', 'ADC', 'SUP', 'A', NULL, NULL),
    (875, 'Sett', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Sett.png', 'TOP', 'SUP', 'A', NULL, NULL),
    (876, 'Lillia', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lillia.png', 'JUNGLE', 'TOP', 'A', NULL, NULL),
    (887, 'Gwen', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Gwen.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (888, 'Renata Glasc', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Renata.png', 'SUP', 'MID', 'A', NULL, NULL),
    (893, 'Aurora', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Aurora.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (895, 'Nilah', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nilah.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (897, 'K''Sante', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/KSante.png', 'TOP', 'JUNGLE', 'A', NULL, NULL),
    (901, 'Smolder', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Smolder.png', 'ADC', 'MID', 'A', NULL, NULL),
    (902, 'Milio', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Milio.png', 'SUP', 'ADC', 'A', NULL, NULL),
    (904, 'Zaahen', 'https://ddragon.leagueoflegends.com/cdn/16.7.1/img/champion/Zaahen.png', 'MID', 'JUNGLE', 'A', NULL, NULL),
    (910, 'Hwei', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Hwei.png', 'SUP', 'MID', 'A', NULL, NULL),
    (950, 'Naafiri', 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Naafiri.png', 'MID', 'JUNGLE', 'A', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
                               name = EXCLUDED.name,
                               image_url = EXCLUDED.image_url,
                               primary_role = EXCLUDED.primary_role,
                               secondary_role = EXCLUDED.secondary_role,
                               tier = EXCLUDED.tier,
                               pick_rate = EXCLUDED.pick_rate,
                               win_rate = EXCLUDED.win_rate;